repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: no-commit-to-branch
    - id: requirements-txt-fixer
    - id: check-docstring-first

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      language_version: python3.9

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]